// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuFLf2gS2wkx9OdoHXCyHL5ZgvIMe_ix0',
    appId: '1:657632130033:android:488908d744f14a56fa4a50',
    messagingSenderId: '657632130033',
    projectId: 'mynotes-umair',
    storageBucket: 'mynotes-umair.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk0sLpswJDkrJTx0m3BKyM3AQNdt_jDfQ',
    appId: '1:657632130033:ios:b49c38a857056e90fa4a50',
    messagingSenderId: '657632130033',
    projectId: 'mynotes-umair',
    storageBucket: 'mynotes-umair.appspot.com',
    iosClientId: '657632130033-o9m742m951625g3hptalm7a41h85h7ld.apps.googleusercontent.com',
    iosBundleId: 'com.umair',
  );
}
